[FEAT] add body in readUserApi
BatShu/BatShu-front pull request #21
Opened 2023-10-21 13:00 UTC by HYEOK9

유저조회 에러떠서 보니까 여기도 body가 필요함

2023-10-22 12:34 UTC, bluejoyq requested changes

2023-10-22 12:34 UTC, bluejoyq commented on src/data/backend/users.ts
> +    method: Exclude<keyof typeof API, "headers">,
이거말고 `type TMethod = "GET" | "PUT" | "POST" | "DELETE"...`
이게 나을듯

2023-10-22 12:34 UTC, bluejoyq commented on src/provider/AuthProvider.tsx
> +    if (user != null) {
이미 authStore의 onAuthStateChanged에서 유저 정보를 불러오고 있어서 불필요할듯.

2023-10-22 12:34 UTC, bluejoyq commented on src/data/backend/users.ts
> +  private async sendAuthenticatedRequest<T>(
이거 class니까 base class에 구현해두는게 어때?
class Repository 만들어두고 상속 받아서 쓰게

2023-10-22 12:34 UTC, bluejoyq commented
@HYEOK9 유저 조회는 안그래도 이번에 바뀜 ㅋㅋ 고생했어. 수정사항만 반영하고 머지하면 될듯.

2023-10-22 15:44 UTC, HYEOK9 commented on src/data/backend/users.ts
> +    method: Exclude<keyof typeof API, "headers">,
어차피 GET이랑 POST밖에 안쓸 거 같으니.. ㅇㅋ

2023-10-22 15:46 UTC, HYEOK9 commented on src/provider/AuthProvider.tsx
> +    if (user != null) {
근데 이렇게 안하면 Bearer 토큰 필요한 API(글쓰기, 비디오 업로드 등등)마다 authStore에서 user 불러와서 헤더에 토큰 일일히 넣어줘야하지 않남...

2023-10-22 15:48 UTC, bluejoyq commented on src/provider/AuthProvider.tsx
> +    if (user != null) {
store에 hook 외부에서도 접근 가능! `authStore.getState` 이렇게

2023-10-22 15:48 UTC, HYEOK9 commented on src/data/backend/users.ts
> +  private async sendAuthenticatedRequest<T>(
아 이건 롤백할게 유저조회/등록 get post말고 다 똑같길래 한건데... 조회api바뀐줄 몰랐음😫

2023-10-22 16:01 UTC, HYEOK9 commented on src/provider/AuthProvider.tsx
> +    if (user != null) {
그거 zustand가 initialize될 때 상태라, 컴포넌트 말고 fetcher.ts같은 파일에서 불러서 확인하면 user null값 일걸?

2023-10-22 16:02 UTC, HYEOK9 commented on src/provider/AuthProvider.tsx
> +    if (user != null) {
근데 컴포넌트에서 api 요청할때마다 store불러오기 귀찮아서 넣은거라.. 기본으로 fetch 헤더에 담아주는 방법 뭐 있남

2023-10-23 06:30 UTC, bluejoyq commented on src/provider/AuthProvider.tsx
> +    if (user != null) {
`axios interceptor` 같은거 이야기하는거지?
그냥 axios로 갈아타자. 이번꺼 대충 수정하기 머지해 내가 바꿔놓을게~

2023-10-23 12:23 UTC, merged