[FEAT] api 이쁘게
BatShu/BatShu-front pull request #6
Opened 2023-09-17 07:32 UTC by HYEOK9

2023-09-19 06:38 UTC, bluejoyq requested changes

2023-09-19 06:38 UTC, gene-ss commented on src/domain/apiPaths.ts
이거 경로 별도로 따는 이유는 msw입니당

2023-09-19 06:38 UTC, gene-ss commented on src/domain/apiPaths.ts
이거 queryWrapper 쓸거면 템플릿타입으로 아예 타입도 정하는게 좋지 않을까.
default 타입으로 record쓰고

2023-09-19 06:38 UTC, bluejoyq commented on src/lib/fetcher.ts
체계적으로 api를 사용하시네요. 좋습니다.

2023-09-19 06:38 UTC, bluejoyq commented on src/lib/fetcher.ts
> +    return new Promise(() => {});
에러를 아예 막아버리는 이유가 뭔가요?

2023-09-21 01:34 UTC, HYEOK9 commented on src/domain/apiPaths.ts
원래 따로 뒀다가 response타입도 다 여기있길래 여기에 넣음 따로 둘거면 다 옮기는 쪽으로 안그럼 똑같은 타입 두번 정의해야됨..

2023-09-21 01:35 UTC, HYEOK9 commented on src/lib/fetcher.ts
> +    return new Promise(() => {});
1. 콘솔에서 똑같이 확인가능
2. 에러가 ui가리는 거 싫음
리액트 쿼리는 에러가 ui 안막음?.?.?

2023-09-21 01:41 UTC, bluejoyq commented on src/lib/fetcher.ts
> +    return new Promise(() => {});
@HYEOK9 예압 자체적으로 내부에서 에러 핸들링 하기 때메, 저렇게 쓰면 오히려 isError나 error 리턴 값이 이상해짐!

2023-09-21 01:43 UTC, bluejoyq commented on src/domain/apiPaths.ts
@HYEOK9 어디 공통으로 dto만 정의하고 import하는 방향은 어떤가요!

2023-09-21 01:59 UTC, HYEOK9 commented on src/domain/apiPaths.ts
일단 endpoint만 빼놓음 옮기고 싶은거 있음 옮기고 머지 ㄱ

2023-09-21 02:17 UTC, merged